### ISSUE TITLE
Javascript error on product edit

### ISSUE THREAD

**Issue by ghost** [myparcelnl/prestashop-deprecated#10]
PrestaShop 1.7.6.3

TypeError: f is null

When you edit a product in backoffice.
Coming from productcustomslegacy-v2.3.7.min.js

**Comment by RichardPerdaan** [comment]
Solved with the latest version of the [PrestaShop MyParcel plugin](https://github.com/myparcelnl/prestashop/releases/tag/v1.4.1)
