### ISSUE TITLE
Bug: When 'Aantal dagen vooruit tonen' is 0, evening delivery doesn't show right

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/prestashop-deprecated#11]
When 'Aantal dagen vooruit tonen' is 'Dagen verbergen', evening delivery will show as a second delivery option with title 'Thuis of op het werk bezorgd' with additional fee. 

This is with '1 dag voor uit tonen',  the evening delivery is shown correctly. 

<img width="687" alt="MyParcel 2020-04-23 12-31-25" src="https://user-images.githubusercontent.com/54140706/80089621-81d71d00-855e-11ea-83f8-1b3e8f471b73.png">

This is with 'Geen dagen vooruit tonen',  evening delivery is shown as 'Thuis of op het werk bezorgd'. 

<img width="660" alt="MyParcel 2020-04-23 12-32-50" src="https://user-images.githubusercontent.com/54140706/80089722-a4693600-855e-11ea-86fa-0fbf55786bca.png">

In the order it shows that there was chosen for evening delivery, so it looks like it's only a front end issue.

**Comment by Nikitaverh** [comment]
00742634

**Comment by RichardPerdaan** [comment]
Solved with the latest version of the [PrestaShop MyParcel plugin](https://github.com/myparcelnl/prestashop)
