### ISSUE TITLE
World shipment; state is not included in export and invoicenr

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/prestashop-deprecated#13]
After a world shipment has been exported to MyParcel, the data in the MyParcel backoffice is not complete. A world shipment to the United States doesn't include the state, and if the shipments in question is opened, it will default to the state of Alabama.

With the export the invoicenumber in the backoffice is the same as the ordernumber or description of the shipment (label description).

**Comment by Nikitaverh** [comment]
00763982

**Comment by Nikitaverh** [comment]
In shipments to Australia, the state isnt exported as well!
