### ISSUE TITLE
Rounding issue in calculating shipping costs

### ISSUE THREAD

**Issue by arisschl** [myparcelnl/prestashop-deprecated#17]
Configured shipping costs in PrestaShop is 3.264463 EUR, tax excluded.
On the front-office this is shown as 3.94 EUR, tax included (21%), while it should be 3.95 EUR.

This is because in myparcel.php, method calcPackageShippingCost(), the shipping costs are rounded to 2 decimals.

**Comment by RichardPerdaan** [comment]
Solved with the latest version of the [PrestaShop MyParcel plugin](https://github.com/myparcelnl/prestashop)
