### ISSUE TITLE
1.7.7.0 - Orderstatus automatiseren is niet mogelijk (verzendlabels aanmaken in Prestashop gaat niet)

### ISSUE THREAD

**Issue by Kapotto0** [myparcelnl/prestashop-deprecated#23]
Ik ben net een nieuwe webshop begonnen met Prestashop versie 1.7.7.0 met een Myparcel module versie 2.3.8 voor het aanmaken van labels en verzenden van pakketten. De module werkt goed op 1 belangrijk punt na, het aanmaken van verzendlabels in Prestashop zelf. 

Ik heb de module geconfigureerd zoals beschreven in de handleiding met uitzondering van volgende sub hoofdstuk:
3.2 Orderstatus automatisering
Geef hier aan of je de status "Verzonden" en "Afgeleverd" automatisch wilt neerzetten nadat de order is geëxporteerd naar MyParcel. 

Prestashop 1.7.7.0 geeft niet de mogelijkheid om dit te activeren. Hierdoor moeten alle verzendlabels automatisch aangemaakt worden in Myparcel en nadien de track en trace code gekopieerd worden naar Prestashop. Dit maakt het runnen van een webshop nogal lastig omdat er super veel tijdverlies ontstaat. 

Is dit een bug? Zo ja, wanneer wordt deze verholpen (of gaat er iets mis in mijn eigen configuratie)?

Met vriendelijk groet,

Kevin

**Comment by Kapotto0** [comment]
I just started a new webshop with Prestashop version 1.7.7.0 with a Myparcel module version 2.3.8 for creating labels and sending packages. The module works well except for 1 important point, the creation of shipping labels in Prestashop itself. 

I have configured the module as described in the manual, with the exception (not available) of the following sub chapter: 3.2 
Order status automation 
Indicate here whether you want to automatically set the status "Sent" and "Delivered" after the order has been exported to MyParcel. 

Prestashop 1.7.7.0 does not provide the option to activate this (order status automation). As a result, all shipping labels must be automatically created in Myparcel and afterwards the track and trace code must be copied to Prestashop. This makes running a webshop rather difficult because there is a lot of time loss. Is this a bug? If so, when will it be fixed (or is something going wrong in my own configuration)? 

Kind regards, Kevin

**Comment by RichardPerdaan** [comment]
Solved with the latest version of the [PrestaShop MyParcel plugin](https://github.com/myparcelnl/prestashop)
