### ISSUE TITLE
Missing index on myparcel_delivery_option.id_cart makes order screen very slow

### ISSUE THREAD

**Issue by Xesau** [myparcelnl/prestashop-deprecated#24]
Once your orders table get sufficiently full, it will take up to 30 seconds to load the orders page.
Adding a simple `INDEX(id_cart)` brings it back to <1s. I suggest this is added to the install script & applied automatically when people next update the module.

**Comment by RichardPerdaan** [comment]
Solved with the latest version of the [PrestaShop MyParcel plugin](https://github.com/myparcelnl/prestashop)
