### ISSUE TITLE
Feature request: tracking-URL 

### ISSUE THREAD

**Issue by NikitaMyParcel** [myparcelnl/prestashop-deprecated#9]
Client would like to auto fill in the tracking URL in the carrier section. It should provide the tracking-url when the standard url is filled in where @ should be the trackingnumber. With PostNL, it should also provide the postalcode to create a working URL.

**Comment by Nikitaverh** [comment]
<img width="1177" alt="Vervoerders   PostNL • MyParcel 2020-03-19 17-26-13" src="https://user-images.githubusercontent.com/54140706/77089984-d68af380-6a06-11ea-90a3-b1c7c4d00bf2.png">

**Comment by Nikitaverh** [comment]
00721919

**Comment by coMegaWebMaster** [comment]
I have done this by modifying 5 core file of PrestaShop, you have to know that MyParcel cannot do this for you as what you are asking is for all carriers in that section and it has to work in the FO & BO.

**Comment by RichardPerdaan** [comment]
Solved with the latest version of the [PrestaShop MyParcel plugin](https://github.com/myparcelnl/prestashop)
